apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 8760h # 1 year
  renewBefore: 360h
  subject:
    organizations:
    - ArgoCD
  commonName: localhost
  dnsNames:
  - localhost
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
