apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  project: otel-demo-project
  source:
    repoURL: git@github.com:avillela/ai-sre-workflow-demo.git
    path: src/otel
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    # automated:
    #   prune: true
    #   selfHeal: true
